rbac:
  create: true
  pspEnabled: false
extraContainers:
  - name: pgbouncer
    image: edoburu/pgbouncer:latest
    ports:
      - name: pgbouncer
        containerPort: 6432
    env:
      - name: DB_HOST
        value: "postgres-host"
config:
  datasource:
    host: localhost
    port: 6432
    password: "password"
